# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLYbRAae56UI0VxoQdiq1Ny5cyB4yOka
"""

import math
class Punto2D:
    """Representacion de punto en 2 dimensiones"""

    def __init__(self, x, y):
      self.x = x
      self.y = y

    def get_x(self):
      return self.x

    def get_y(self):
    	return self.y

    def polar_radius(self):
      return math.sqrt(x*x + y*y)

    def polar_angle(self, x, y):
      angulo = math.atan2(y,x)
      return math.radians(angulo)

    def dist_euclidiana(self, other):
      return math.sqrt(((self.x-other.x)**2)+((self.y-other.y)**2))

punto_1 = Punto2D(10,20)
punto_2 = Punto2D(0,0)

punto_1.dist_euclidiana(punto_2)

punto_1.polar_angle(10,20)