# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17d3OWMTQRBO9GVwRjfmffMYy3uwN0cQf
"""

def hanoi(n,inicio,fin,aux):
  if n == 1 :
    print(inicio+"--> "+fin)
  else:
    hanoi(n-1,inicio,aux,fin)
    print(inicio+ "--> "+fin)
    hanoi(n-1,aux,fin,inicio)

hanoi(3,"0","2","1")